
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MONSTERS=[
 {name:'火焰龍',icon:'🔥',color:'#ff814e',dark:'#dc543e',accent:'#ffcf5e',energy:'#ff8a31',shape:'dragon'},
 {name:'雷電獸',icon:'⚡',color:'#ffcc48',dark:'#e9a63f',accent:'#fff19c',energy:'#ffdc36',shape:'bolt'},
 {name:'水滴獸',icon:'💧',color:'#59c6ef',dark:'#3798d1',accent:'#c6f5ff',energy:'#65d8fa',shape:'drop'},
 {name:'森林獸',icon:'🌿',color:'#79cf74',dark:'#4ca365',accent:'#c8f19b',energy:'#7ae98a',shape:'forest'},
 {name:'機器獸',icon:'🤖',color:'#a9b9d4',dark:'#6e87ab',accent:'#e9f6ff',energy:'#8ad7ff',shape:'robot'},
 {name:'星光獸',icon:'⭐',color:'#bd9bf3',dark:'#9270d0',accent:'#ffe697',energy:'#e5bbff',shape:'star'}
];
const DEFAULT={tables:[...TABLES],questionMode:'random',battleMode:'timed',duration:60,maxHp:100,penalty:5,combo:true,monsters:[0,1],sound:true,music:false};
const PRESETS={beginner:{tables:[2,3,4,5],maxHp:100,penalty:5,combo:false,duration:90},standard:{tables:[...TABLES],maxHp:100,penalty:5,combo:true,duration:60},challenge:{tables:[6,7,8,9],maxHp:100,penalty:10,combo:true,duration:60}};
function readSettings(){try{const x=JSON.parse(localStorage.getItem('monsterBattleSettings'));return {...DEFAULT,...x,tables:Array.isArray(x?.tables)&&x.tables.length?x.tables:DEFAULT.tables};}catch{return {...DEFAULT};}}
function saveSettings(){try{localStorage.setItem('monsterBattleSettings',JSON.stringify(settings));}catch{}}
let settings=readSettings(),state='HOME',players=[],bossHp=500,timer=60,deadline=0,tickId=null,vsTimeout=null,countTimeout=null,countStep=0,confirmAction=null,attackTimeouts=[],deferred=[];
const audio=new AudioManager(); audio.sound=settings.sound;audio.music=settings.music;
const qgen=new QuestionGenerator();
function monsterSvg(index){const m=MONSTERS[index], extra={
 dragon:`<path d="M47 82 Q5 55 21 21 L62 53Z" fill="${m.dark}"/><path d="M153 82 Q195 55 179 21 L138 53Z" fill="${m.dark}"/><path d="M78 43 L66 7 L93 30 L110 0 L122 44" fill="${m.accent}"/><path d="M40 128 Q4 118 12 93 L47 105" fill="${m.dark}"/>`,
 bolt:`<path d="M45 74 L17 37 L67 49 L83 8 L92 52" fill="${m.accent}"/><path d="M153 74 L185 35 L139 47 L123 10 L109 54" fill="${m.accent}"/><path d="M32 125 L6 147 L45 140" fill="${m.dark}"/>`,
 drop:`<path d="M100 3 C73 42 35 67 35 104 C35 151 65 175 100 175 C135 175 165 151 165 104 C165 67 127 42 100 3Z" fill="${m.color}" stroke="${m.dark}" stroke-width="7"/><ellipse cx="66" cy="91" rx="13" ry="25" fill="${m.accent}" opacity=".7"/>`,
 forest:`<path d="M57 58 Q16 48 30 8 Q66 15 76 53" fill="${m.dark}"/><path d="M143 58 Q184 48 170 8 Q134 15 124 53" fill="${m.dark}"/><path d="M65 38 Q87 13 100 39 Q113 13 135 38" fill="${m.accent}"/>`,
 robot:`<rect x="37" y="47" width="126" height="115" rx="26" fill="${m.color}" stroke="${m.dark}" stroke-width="7"/><path d="M100 45 V17" stroke="${m.dark}" stroke-width="8"/><circle cx="100" cy="14" r="10" fill="${m.accent}"/><rect x="51" y="69" width="98" height="55" rx="17" fill="#3a5c80"/>`,
 star:`<path d="M100 6 L123 48 L171 40 L151 83 L185 117 L137 123 L118 166 L100 145 L82 166 L63 123 L15 117 L49 83 L29 40 L77 48Z" fill="${m.accent}" stroke="${m.dark}" stroke-width="6"/>`
 }[m.shape];
 const body=m.shape==='drop'||m.shape==='robot'||m.shape==='star'?'':`<ellipse cx="100" cy="107" rx="65" ry="67" fill="${m.color}" stroke="${m.dark}" stroke-width="7"/><ellipse cx="100" cy="141" rx="35" ry="25" fill="${m.accent}" opacity=".7"/>`;
 const eyes=m.shape==='robot'?`<g class="eyes"><circle cx="77" cy="94" r="9" fill="#a8faff"/><circle cx="123" cy="94" r="9" fill="#a8faff"/></g>`:`<g class="eyes"><ellipse cx="77" cy="99" rx="9" ry="12" fill="#233653"/><ellipse cx="123" cy="99" rx="9" ry="12" fill="#233653"/><circle cx="80" cy="94" r="3" fill="white"/><circle cx="126" cy="94" r="3" fill="white"/></g>`;
 return `<svg class="monster-svg" viewBox="0 0 200 190" role="img" aria-label="${m.name}"><g class="monster-shell">${extra}${body}<ellipse cx="60" cy="150" rx="17" ry="10" fill="${m.dark}"/><ellipse cx="140" cy="150" rx="17" ry="10" fill="${m.dark}"/>${eyes}<path d="M91 126 Q100 135 109 126" fill="none" stroke="#74464c" stroke-width="4" stroke-linecap="round"/><circle cx="56" cy="121" r="10" fill="#ff9990" opacity=".55"/><circle cx="144" cy="121" r="10" fill="#ff9990" opacity=".55"/></g></svg>`;
}
function show(name){state=name;const id={CHARACTER_SELECT:'select',SETTINGS:'settings',HELP:'help',HOME:'home',VS:'vs',PLAYING:'game',RESULT:'result'}[name];$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));}
function settingsToForm(){ $('#tables').innerHTML=TABLES.map(n=>`<label class="${settings.tables.includes(n)?'checked':''}"><input type="checkbox" value="${n}" ${settings.tables.includes(n)?'checked':''}>${n}</label>`).join('');$('#questionMode').value=settings.questionMode;$('#battleMode').value=settings.battleMode;$('#duration').value=settings.duration;$('#maxHp').value=settings.maxHp;$('#penalty').value=settings.penalty;$('#combo').value=settings.combo?'on':'off';}
function formToSettings(){settings.tables=$$('#tables input:checked').map(x=>Number(x.value));if(!settings.tables.length){settings.tables=[2];settingsToForm()}settings.questionMode=$('#questionMode').value;settings.battleMode=$('#battleMode').value;settings.duration=Number($('#duration').value);settings.maxHp=Number($('#maxHp').value);settings.penalty=Number($('#penalty').value);settings.combo=$('#combo').value==='on';saveSettings();}
function selectScreen(){formToSettings();$('#name0').value=players[0]?.name||'玩家 1';$('#name1').value=players[1]?.name||'玩家 2';renderCards();show('CHARACTER_SELECT');}
function renderCards(){for(let p=0;p<2;p++){$(`#cards${p}`).innerHTML=MONSTERS.map((m,i)=>`<button class="monster-card ${settings.monsters[p]===i?'selected':''}" data-player="${p}" data-monster="${i}" aria-label="玩家 ${p+1} 選擇${m.name}" aria-pressed="${settings.monsters[p]===i}">${monsterSvg(i)}<span>${m.icon} ${m.name}</span></button>`).join('');}}
function newPlayer(i){return {name:$(`#name${i}`).value.trim()||`玩家 ${i+1}`,monster:settings.monsters[i],hp:settings.maxHp,score:0,correct:0,wrong:0,combo:0,bestCombo:0,wrongQuestions:{},question:null,locked:false,lastAnswerAt:0,sequence:0};}
function startBattle(){clearGameTimers();players=[newPlayer(0),newPlayer(1)];bossHp=500;timer=settings.duration;saveSettings();$('#vs0').innerHTML=monsterSvg(players[0].monster)+`<span class="vs-name"></span>`+' · '+MONSTERS[players[0].monster].name;$('#vs1').innerHTML=monsterSvg(players[1].monster)+`<span class="vs-name"></span>`+' · '+MONSTERS[players[1].monster].name;$('#vs0 .vs-name').textContent=players[0].name;$('#vs1 .vs-name').textContent=players[1].name;show('VS');vsTimeout=setTimeout(startCountdown,1750);}
function startCountdown(){clearTimeout(vsTimeout);if(state!=='VS')return;show('COUNTDOWN');setupGame();$('#game').classList.add('active');$('#countdownOverlay').classList.remove('hidden');countStep=3;countdownTick();}
function countdownTick(){if(state!=='COUNTDOWN')return;$('#countdownText').textContent=countStep||'GO!';$('#countdownText').style.animation='none';void $('#countdownText').offsetWidth;$('#countdownText').style.animation='';audio.play(countStep?'count':'go');if(countStep===0){countTimeout=setTimeout(()=>{$('#countdownOverlay').classList.add('hidden');show('PLAYING');deadline=performance.now()+timer*1000;tickId=setInterval(tick,100);audio.startMusic();},650);}else{countStep--;countTimeout=setTimeout(countdownTick,750);}}
function setupGame(){ $('#arena').classList.toggle('boss-mode',settings.battleMode==='boss');$('#bossBox').classList.toggle('hidden',settings.battleMode!=='boss');$('#fighterBoss').classList.toggle('hidden',settings.battleMode!=='boss');$('#fighterBoss').innerHTML=monsterSvg(4);$('#fighter0').innerHTML=monsterSvg(players[0].monster);$('#fighter1').innerHTML=monsterSvg(players[1].monster);$('#modeLabel').textContent={timed:'⏱ 限時對戰',ko:'🥊 KO 對戰',boss:'🤝 合作魔王'}[settings.battleMode];$('#timerBox').classList.toggle('hidden',settings.battleMode==='ko');$('#arenaTitle').textContent=settings.battleMode==='boss'?'聯手挑戰大魔王':'怪獸競技場';$('#arenaMessage').textContent='';$('#finalCountdown').textContent='';$('#timer').textContent=timer;$('#bossHp').textContent='500 / 500';$('#bossBar').style.width='100%';for(let i=0;i<2;i++){players[i].question=qgen.next(players[i],settings);renderPlayer(i);}}
function renderPlayer(i){const p=players[i],keys=i===0?['Q','W','E']:['I','O','P'];$(`#player${i}`).innerHTML=`<div class="player-title"><span>${i===0?'🔵':'🔴'} <span class="player-name"></span></span><span class="player-score">⭐ <span class="score">0</span></span></div><div class="hp-label"><span>❤️ HP</span><span class="hp-text">${p.hp} / ${settings.maxHp}</span></div><div class="hp-track"><div class="hp-fill"></div></div><div class="mini-stats"><span>✓ 正確 <b class="correct-count">0</b></span><span>✕ 錯誤 <b class="wrong-count">0</b></span></div><div class="combo-badge">🔥 COMBO ×<span class="combo">0</span></div><div class="question-box"><div class="question-label">請選出正確答案</div><div class="question"></div></div><div class="answers"></div><div class="key-hint">鍵盤 ${keys.join('　')}</div>`;$(`#player${i} .player-name`).textContent=p.name;renderQuestion(i);updatePlayer(i);}
function renderQuestion(i){const p=players[i],box=$(`#player${i}`);box.querySelector('.question').textContent=`${p.question.a} × ${p.question.b} = ?`;box.querySelector('.answers').innerHTML=p.question.answers.map((n,j)=>`<button class="answer" data-answer-player="${i}" data-answer-index="${j}" aria-label="${n}，鍵盤 ${i===0?['Q','W','E'][j]:['I','O','P'][j]}">${n}</button>`).join('');}
function updatePlayer(i){const p=players[i],box=$(`#player${i}`);box.querySelector('.score').textContent=p.score;box.querySelector('.hp-text').textContent=`${p.hp} / ${settings.maxHp}`;const bar=box.querySelector('.hp-fill');bar.style.width=`${100*p.hp/settings.maxHp}%`;bar.classList.toggle('low',p.hp/settings.maxHp<.3);box.querySelector('.correct-count').textContent=p.correct;box.querySelector('.wrong-count').textContent=p.wrong;box.querySelector('.combo').textContent=p.combo;box.querySelector('.combo-badge').classList.toggle('super',settings.combo&&p.combo>=5);$(`#fighter${i}`).classList.toggle('tired',p.hp/settings.maxHp<.3);}
function answer(i,j){if(state!=='PLAYING')return;const p=players[i];if(p.locked||!p.question||j<0||j>2)return;p.locked=true;const choice=p.question.answers[j],right=choice===p.question.correct,btns=$$(`#player${i} .answer`);btns.forEach(b=>b.disabled=true);btns[j].classList.add(right?'correct':'wrong');btns[j].textContent=`${right?'✓':'✕'} ${choice}`;p.lastAnswerAt=performance.now();
 if(right){p.correct++;p.combo++;p.bestCombo=Math.max(p.bestCombo,p.combo);const power=settings.combo?(p.combo>=5?20:p.combo>=3?15:10):10;p.score+=power;audio.play(p.combo>=5&&settings.combo?'super':p.combo>=3&&settings.combo?'combo':'correct');$(`#player${i} .player-score`).classList.remove('bump');void $(`#player${i} .player-score`).offsetWidth;$(`#player${i} .player-score`).classList.add('bump');attack(i,power);}else{p.wrong++;p.combo=0;p.wrongQuestions[p.question.key]=(p.wrongQuestions[p.question.key]||0)+1;p.hp=Math.max(0,p.hp-settings.penalty);audio.play('wrong');$(`#fighter${i}`).classList.add('hurt');setTimeout(()=>$(`#fighter${i}`).classList.remove('hurt'),500);if(settings.penalty)damageNumber(i,settings.penalty,true);}
 updatePlayer(i);if(p.hp===0){finish(settings.battleMode==='boss'?'bossFail':'ko',1-i);return;}if(state!=='PLAYING')return;
 setTimeout(()=>{const next=()=>{if(state!=='PLAYING')return;p.question=qgen.next(p,settings);p.locked=false;renderQuestion(i);};if(state==='PAUSED')deferred.push(next);else next();},430);
}
function attack(i,power){const target=settings.battleMode==='boss'?'Boss':String(1-i),attacker=$(`#fighter${i}`),victim=$(`#fighter${target}`),m=MONSTERS[players[i].monster];attacker.classList.remove('attack-left','attack-right');void attacker.offsetWidth;attacker.classList.add(i===0?'attack-left':'attack-right');setTimeout(()=>attacker.classList.remove('attack-left','attack-right'),500);const orb=document.createElement('div');orb.className=`projectile ${i===1?'reverse':''} ${target==='Boss'?'to-boss':''} ${i===1&&target==='Boss'?'from-right':''}`;orb.style.setProperty('--energy',m.energy);$('#effectLayer').appendChild(orb);setTimeout(()=>orb.remove(),600);if(settings.combo&&players[i].combo>=3)message(players[i].combo>=5?'💥 SUPER ATTACK!':'🔥 COMBO ATTACK!');
 const hit=setTimeout(()=>{const resolve=()=>{if(state!=='PLAYING')return;audio.play('attack');victim.classList.add('hurt');setTimeout(()=>victim.classList.remove('hurt'),500);damageNumber(target,power);if(target==='Boss'){bossHp=Math.max(0,bossHp-power);$('#bossBar').style.width=`${bossHp/5}%`;$('#bossHp').textContent=`${bossHp} / 500`;if(bossHp===0)finish('bossWin');}else{players[Number(target)].hp=Math.max(0,players[Number(target)].hp-power);updatePlayer(Number(target));if(players[Number(target)].hp===0)finish('ko',i);}};if(state==='PAUSED')deferred.push(resolve);else resolve();},310);attackTimeouts.push(hit);
}
function damageNumber(target,n,self=false){const el=document.createElement('div');el.className='damage';el.textContent=`−${n} HP`;el.style.left=target==='Boss'?'42%':target===0?'11%':'67%';if(self)el.style.color='#ffd47b';$('#effectLayer').appendChild(el);setTimeout(()=>el.remove(),1050);}
function message(s){const el=$('#arenaMessage');el.textContent=s;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');}
function tick(){if(state!=='PLAYING')return;const remaining=Math.max(0,Math.ceil((deadline-performance.now())/1000));if(remaining!==timer){timer=remaining;$('#timer').textContent=timer;$('#timerBox').classList.toggle('urgent',timer<=10);$('#finalCountdown').textContent=timer<=10&&timer>0?timer:'';if(timer<=10&&timer>0)audio.play('count');}if(timer===0)finish(settings.battleMode==='boss'?'bossFail':'time');}
function pause(){if(state!=='PLAYING')return;timer=Math.max(0,Math.ceil((deadline-performance.now())/1000));clearInterval(tickId);audio.stopMusic();show('PAUSED');$('#game').classList.add('active','paused');$('#pauseOverlay').classList.remove('hidden');}
function resume(){if(state!=='PAUSED')return;$('#pauseOverlay').classList.add('hidden');$('#game').classList.remove('paused');show('PLAYING');deadline=performance.now()+timer*1000;tickId=setInterval(tick,100);audio.startMusic();const tasks=deferred.splice(0);tasks.forEach(fn=>fn());}
function finish(reason,winner){if(state==='RESULT')return;clearGameTimers();state='RESULT';$('#pauseOverlay').classList.add('hidden');$('#countdownOverlay').classList.add('hidden');$('#game').classList.remove('active');let title='',sub='';if(reason==='bossWin'){title='合作成功！打倒魔王！';sub='兩位乘法英雄一起守護了競技場！';}else if(reason==='bossFail'){title='魔王還在等你們挑戰！';sub=`魔王剩下 ${bossHp} HP，再合作一次吧！`;}else{if(reason==='time'){if(players[0].hp>players[1].hp)winner=0;else if(players[1].hp>players[0].hp)winner=1;else if(players[0].score>players[1].score)winner=0;else if(players[1].score>players[0].score)winner=1;else winner=-1;}title=winner===-1?'精彩平手！':`${players[winner].name} 勝利！`;sub=reason==='ko'?'怪獸 KO！精彩的乘法對決。':'時間到！先比 HP，平手再比分數。';}$('#resultTitle').textContent=title;$('#resultSubtitle').textContent=sub;$('#resultStats').innerHTML=players.map((p,i)=>{const accuracy=p.correct+p.wrong?Math.round(p.correct/(p.correct+p.wrong)*100):0;const title=p.bestCombo>=5?'🔥 Combo 大師':accuracy>=85&&p.correct>=3?'🎯 神準算術王':p.correct>=8?'⚡ 快速答題王':'🌱 勇敢挑戰者';return `<div class="result-card ${i?'red':''}">${monsterSvg(p.monster)}<h3>${i?'🔴':'🔵'} <span class="result-name"></span></h3><p>⭐ 分數：${p.score}</p><p>❤️ HP：${p.hp} / ${settings.maxHp}</p><p>✓ 答對：${p.correct}　✕ 答錯：${p.wrong}</p><p>🎯 正確率：${accuracy}%　🔥 最長連擊：${p.bestCombo}</p><span class="title-chip">${title}</span></div>`}).join('');$$('.result-name').forEach((el,i)=>el.textContent=players[i].name);$('#confetti').innerHTML=Array.from({length:35},(_,i)=>`<i class="confetti-piece" style="--left:${Math.random()*100}%;--turn:${Math.random()*360}deg;--delay:${Math.random()*-4}s;--color:${['#ffcb4c','#f26b75','#66c5ef','#78d589'][i%4]}"></i>`).join('');show('RESULT');audio.play('win');}
function clearGameTimers(){clearInterval(tickId);clearTimeout(vsTimeout);clearTimeout(countTimeout);attackTimeouts.forEach(clearTimeout);attackTimeouts=[];deferred=[];audio.stopMusic();$('#game').classList.remove('paused');$('#effectLayer').innerHTML='';}
function home(){clearGameTimers();$('#pauseOverlay').classList.add('hidden');$('#confirmOverlay').classList.add('hidden');$('#countdownOverlay').classList.add('hidden');$('#game').classList.remove('active');show('HOME');}
function confirm(kind){confirmAction=kind;$('#confirmTitle').textContent=kind==='restart'?'重新開始這場對戰？':'回到首頁？';$('#confirmOverlay').classList.remove('hidden');}
function action(name){audio.play('button');switch(name){case'home':home();break;case'settings':settingsToForm();show('SETTINGS');break;case'help':show('HELP');break;case'select':selectScreen();break;case'replay':show('CHARACTER_SELECT');startBattle();break;case'resume':resume();break;case'restartConfirm':confirm('restart');break;case'homeConfirm':confirm('home');break;}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)action(a.dataset.action);const c=e.target.closest('[data-monster]');if(c){settings.monsters[Number(c.dataset.player)]=Number(c.dataset.monster);saveSettings();renderCards();audio.play('button');}const ans=e.target.closest('[data-answer-player]');if(ans)answer(Number(ans.dataset.answerPlayer),Number(ans.dataset.answerIndex));const preset=e.target.closest('[data-preset]');if(preset){settings={...settings,...PRESETS[preset.dataset.preset]};settingsToForm();$$('[data-preset]').forEach(b=>b.classList.toggle('selected',b===preset));saveSettings();audio.play('button');}});
$('#tables').addEventListener('change',e=>{e.target.closest('label')?.classList.toggle('checked',e.target.checked);formToSettings();});$$('.setting-box select').forEach(x=>x.addEventListener('change',()=>{formToSettings();$$('[data-preset]').forEach(b=>b.classList.remove('selected'));}));
$('#battleStart').addEventListener('click',startBattle);$('#pauseBtn').addEventListener('click',pause);$('#confirmYes').addEventListener('click',()=>{const target=confirmAction;$('#confirmOverlay').classList.add('hidden');if(target==='restart'){show('CHARACTER_SELECT');startBattle();}else home();});$('#confirmNo').addEventListener('click',()=>$('#confirmOverlay').classList.add('hidden'));
$('#soundBtn').addEventListener('click',()=>{settings.sound=!settings.sound;audio.sound=settings.sound;$('#soundBtn').textContent=settings.sound?'🔊 音效':'🔇 靜音';saveSettings();audio.play('button');});$('#musicBtn').addEventListener('click',()=>{settings.music=!settings.music;audio.music=settings.music;$('#musicBtn').textContent=settings.music?'🎵 BGM ON':'🎵 BGM OFF';saveSettings();if(state==='PLAYING')settings.music?audio.startMusic():audio.stopMusic();});$('#fullBtn').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});});
document.addEventListener('keydown',e=>{if(e.repeat||['INPUT','SELECT'].includes(document.activeElement?.tagName))return;if(state==='VS'){startCountdown();return;}if(state==='PLAYING'){const k=e.key.toUpperCase(),p0=['Q','W','E'].indexOf(k),p1=['I','O','P'].indexOf(k);if(p0>=0)answer(0,p0);if(p1>=0)answer(1,p1);if(k==='ESCAPE')pause();}else if(state==='PAUSED'&&e.key==='Escape')resume();});$('#vs').addEventListener('click',startCountdown);
$('#homeMonsters').innerHTML=`<div class="home-monster">${monsterSvg(0)}</div><div class="home-monster">${monsterSvg(1)}</div>`;$('#soundBtn').textContent=settings.sound?'🔊 音效':'🔇 靜音';$('#musicBtn').textContent=settings.music?'🎵 BGM ON':'🎵 BGM OFF';settingsToForm();show('HOME');
